"""画像説明文カラム追加

Revision ID: 09bb37a465c3
Revises: f7984c28133a
Create Date: 2022-06-04 07:49:21.349916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bb37a465c3'
down_revision = 'f7984c28133a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('alt', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'alt')
    # ### end Alembic commands ###
