"""NavLinkの削除

Revision ID: 118ade005bd4
Revises: 64dcbe1d3e56
Create Date: 2022-06-16 12:28:56.897532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118ade005bd4'
down_revision = '64dcbe1d3e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nav_links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nav_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('left_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nav_links_pkey')
    )
    # ### end Alembic commands ###
