"""navbarタイトル

Revision ID: 64dcbe1d3e56
Revises: 7a6d16c0fe71
Create Date: 2022-06-14 06:30:37.498518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dcbe1d3e56'
down_revision = '7a6d16c0fe71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nav_links', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nav_links', 'title')
    # ### end Alembic commands ###
