"""navbarリンク

Revision ID: 7a6d16c0fe71
Revises: a0a0881d6b0c
Create Date: 2022-06-14 06:27:54.128327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6d16c0fe71'
down_revision = 'a0a0881d6b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nav_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left_num', sa.Integer(), nullable=True),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nav_links')
    # ### end Alembic commands ###
