"""次世代画像フォーマットのURLを追加

Revision ID: 80cad0029c15
Revises: 118ade005bd4
Create Date: 2022-08-01 18:46:13.740394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80cad0029c15'
down_revision = '118ade005bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('avif_url', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('webp_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'webp_url')
    op.drop_column('items', 'avif_url')
    # ### end Alembic commands ###
